apiVersion: v1
kind: Pod
metadata:
  labels:
    test: envvar
  name: envar-test
spec:
  containers:
    - env:
      - name: VARIABLE1
        value: "mi valor"
      - name: VARIABLE2
        value: "mi valor 2"
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: POD_HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: POD_PHASE
        valueFrom:
          fieldRef:
            fieldPath: status.phase
      name: envar-test
      image: nginx:alpine
