apiVersion: v1
kind: Pod
metadata:
  name: limit-cpu-3
spec:
  containers:
  - name: limit-cpu-3
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args: ["-cpus","2"]
