---
apiVersion: v1
kind: Namespace
metadata:
  name: develop
  labels:
    name: develop
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-develop
  namespace: develop
spec:
  limits:
  - default:
      memory: 256Mi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 1
    max:
      memory: 512Mi
      cpu: 2
    min:
      memory: 100Mi
      cpu: 0.1
    type: Container
