apiVersion: v1
kind: Pod
metadata:
  name: limit-cpu
spec:
  containers:
  - name: limit-cpu
    image: vish/stress
    resources:
      limits:
        cpu: "1000m"
      requests:
        cpu: "500m"
    args: ["-cpus","2"]
