apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-ns-default
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 2
    defaultRequest:
      memory: 512Mi
      cpu: 2
    type: Container
