apiVersion: v1
kind: Pod
metadata:
  name: default-mem-demo-guara
spec:
  containers:
  - name: default-mem-demo-guara
    image: nginx
    resources:
      limits:
        memory: 512Mi
        cpu: 1
      requests:
        memory: 512Mi
        cpu: 1
