apiVersion: v1
kind: Pod
metadata:
  name: limit-ram-2
spec:
  containers:
  - name: limit-ram-2
    image: polinux/stress
    resources:
      limits:
        memory: 500Mi
      requests:
        memory: 128Mi
    command: ["stress"]
    args: ["--vm","1", "--vm-bytes","300M","--vm-hang","1"]
