apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-26T16:47:17Z"
  labels:
    app: nginx
  name: nginx-deployment
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
