apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs01
  labels:
    app: app01
    tier: app01
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: app01
  template:
    metadata:
      labels:
        tier: app01
    spec:
      containers:
      - name: cont1
        image: nginx:alpine
