apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: service1
  namespace: default
spec:
  externalIPs:
  - 192.168.1.102
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  selector:
    app: nginx
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: service2
  namespace: default
spec:
  externalIPs:
  - 192.168.1.103
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  selector:
    app: nginx
  type: ClusterIP
status:
  loadBalancer: {}
