apiVersion: v1
kind: Pod
metadata:
  labels:
    test: startupprobe
  name: startup-http
spec:
  containers:
  - name: startup
    image: k8s.gcr.io/liveness
    args:
    - /server
    startupProbe:
      httpGet:
        path: /healthz
        port: 8081
      failureThreshold: 30
      periodSeconds: 10

