apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-deployment
  namespace: default
spec:
  externalIPs:
  - 192.168.99.102
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  selector:
    app: nginx
  type: ClusterIP
status:
  loadBalancer: {}

