apiVersion: v1
kind: Pod
metadata:
  name: test-volumen1
  labels:
    app: volumes01
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-vol
  volumes:
    - name: www-vol
      hostPath:
        path: ./www-vol
        type: Directory
