apiVersion: v1
kind: Pod
metadata:
  name: test-volumen1
  labels:
    app: volumes01
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-vol-nfs
  volumes:
    - name: www-vol-nfs
      nfs:
        path: /media/nfs
        server: 10.1.6.254
        readOnly: false
