apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ClusterRoleRW
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["*"]
  resources: ["pods","replicaset","services","deployment"]
  verbs: ["create","delete","get", "watch", "list"]
