kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: CRB-rw-role
subjects:
- kind: User
  name: myusuario1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ClusterRoleRW
  apiGroup: rbac.authorization.k8s.io
