kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: RB-read-only-role
  namespace: qa
subjects:
- kind: User
  name: myusuario1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-only-role
  apiGroup: rbac.authorization.k8s.io
