apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: minamespace
  name: RoleRW
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["*"]
  resources: ["pods","replicaset","services","deployment"]
  verbs: ["create","delete","get", "watch", "list"]
