kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: RB-rw-role
  namespace: minamespace
subjects:
- kind: User
  name: myusuario1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: RoleRW
  apiGroup: rbac.authorization.k8s.io
