apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-volume
  labels:
    type: nfs1
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media/nfs
    server: 10.1.6.254
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypv-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: nfs1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-pvc
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: mypv-volume-storage
      volumes:
        - name: mypv-volume-storage
          persistentVolumeClaim:
            claimName: mypv-volume-claim

