apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-volume2
  labels:
    type: nfs2
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media/nfs
    server: 10.1.6.254
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-volume1
  labels:
    type: nfs1
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media/nfs
    server: 10.1.6.254
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypv-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: nfs1
