apiVersion: v1
kind: Pod
metadata:
  name: pod-simple
spec:
  containers:
  - name: pod-simple
    image: nginx:alpine
    volumeMounts:
      - name: pod-simple
        mountPath: /etc/nginx/conf.d/
  volumes:
    - name: pod-simple
      configMap:
        name: pod-simple
  
