apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypv-volume-claim2
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

