apiVersion: v1
kind: Pod
metadata:
  name: out-of-memory-killer
spec:
  containers:
  - name: out-of-memory-killer
    image: polinux/stress
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
    command: ["stress"]
    args: ["--vm","1", "--vm-bytes","1024M","--vm-hang","1"]

