apiVersion: v1
kind: Secret
metadata:
  name: misecreto
type: Opaque
stringData:
  username: admin
  password: t0p-Secret
---
apiVersion: v1
kind: Pod
metadata:
  name: podsecrets
spec:
  containers:
  - name: podsecrets
    image: nginx:alpine
    volumeMounts:
      - name: podsecrets
        mountPath: /etc/auth/
  volumes:
    - name: podsecrets
      secret:
        secretName: misecreto
        items:
        - key: password
          path: my-password.txt

