apiVersion: v1
kind: Secret
metadata:
  name: misecreto
type: Opaque
stringData:
  username: admin
  password: t0p-Secret
---
apiVersion: v1
kind: Pod
metadata:
  name: podsecrets-envvar
spec:
  containers:
  - name: podsecrets-envvar
    image: nginx:alpine
    env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: misecreto
            key: password

